name: MajnCraft Auctions
version: 1.0
description: Plugin what gives into game Auctions
# We could place every author in the authors list, but chose not to for illustrative purposes
# Also, having an author distinguishes that person as the project lead, and ensures their 
# name is displayed first
author: siOnzee
authors: [Sekiphp, Sognus] 
website: http://majncraft.cz/

main: cz.sionzee.MajnCraft.Auction.Index
database: false
softdepend: [Vault]

commands:
  ma:
    description: Prefix for all commands
permissions:
  MajnCraft.*:
    description: Gives access to all Auction commands
    children:
      MajnCraft.ban: true
      MajnCraft.password: true
      MajnCraft.create: true
      MajnCraft.money: true
      MajnCraft.pay: true
      MajnCraft.top: true
      MajnCraft.remove: true
      MajnCraft.help: true
  MajnCraft.ban:
    description: Allows you to ban player
    default: op
  MajnCraft.password:
    description: Allows you to protect auction
    default: op
  MajnCraft.create:
    description: Allows you to create auction
    default: op
  MajnCraft.money:
    description: Allows you to show your money
    default: true
  MajnCraft.pay:
    description: Allows you to pay money
    default: true
  MajnCraft.top:
    description: Allows you to show top players
    default: true
  MajnCraft.remove:
    description: Allows you to remove auction
    default: op
  MajnCraft.help:
    description: Allows you to show help
    default: true